services:
  db:
    image: mysql:8.4
    container_name: fitease_mysql
    environment:
      MYSQL_DATABASE: fitease
      MYSQL_USER: fitease
      MYSQL_PASSWORD: fitease
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - fitease_mysql_data:/var/lib/mysql

volumes:
  fitease_mysql_data: